"""
dam/core/exporter.py

Exports container configurations to three formats:

  dam-yaml     — Full ContainerConfig snapshot, re-importable by DAM on any host.
                 Filename: <name>.dam.yaml

  docker-run   — Executable shell script with exact `docker run` command.
                 Works anywhere without DAM installed.
                 Filename: <name>.sh  (or all-containers.sh for multi)

  compose      — Valid docker-compose.yml. One service per container,
                 or full stack in one file for multi-container export.
                 Filename: <name>.compose.yml  (or docker-compose.yml for all)

Design goals:
  - No Docker daemon needed — works purely from ContainerConfig objects
  - Exported files are self-contained and human-readable
  - docker-run scripts are directly executable (chmod +x)
  - compose output is valid and importable by `docker compose up`
  - dam-yaml roundtrips perfectly through importer.py
"""

from __future__ import annotations

import shlex
from datetime import datetime
from pathlib import Path

import yaml

from dam import __version__
from dam.core.inspector import ContainerConfig


# ------------------------------------------------------------
# Export format enum
# ------------------------------------------------------------

FORMATS = ("dam-yaml", "docker-run", "compose")


# ------------------------------------------------------------
# DAM YAML export
# ------------------------------------------------------------

def export_dam_yaml(cfg: ContainerConfig, output_dir: Path) -> Path:
    """
    Export a single ContainerConfig as a DAM YAML file.
    Identical in structure to snapshot files — importable by DAM on any host.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"{cfg.name}.dam.yaml"

    document = {
        "dam_version": __version__,
        "exported_at": datetime.now().isoformat(timespec="seconds"),
        "format": "dam-yaml",
        "container": _config_to_dict(cfg),
    }

    with open(path, "w") as f:
        yaml.dump(document, f, default_flow_style=False, sort_keys=False)

    return path


def export_dam_yaml_multi(configs: list[ContainerConfig], output_dir: Path) -> Path:
    """Export multiple containers into a single DAM YAML file."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "all-containers.dam.yaml"

    document = {
        "dam_version": __version__,
        "exported_at": datetime.now().isoformat(timespec="seconds"),
        "format": "dam-yaml",
        "containers": {cfg.name: _config_to_dict(cfg) for cfg in configs},
    }

    with open(path, "w") as f:
        yaml.dump(document, f, default_flow_style=False, sort_keys=False)

    return path


# ------------------------------------------------------------
# Docker run script export
# ------------------------------------------------------------

def export_docker_run(cfg: ContainerConfig, output_dir: Path) -> Path:
    """
    Export a single container as an executable shell script with the
    exact `docker run` command needed to recreate it.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"{cfg.name}.sh"

    script = _build_docker_run_script([cfg])
    path.write_text(script)
    path.chmod(0o755)
    return path


def export_docker_run_multi(configs: list[ContainerConfig], output_dir: Path) -> Path:
    """Export multiple containers as a single shell script."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "all-containers.sh"

    script = _build_docker_run_script(configs)
    path.write_text(script)
    path.chmod(0o755)
    return path


def _build_docker_run_script(configs: list[ContainerConfig]) -> str:
    """Build a complete shell script for recreating one or more containers."""
    lines = [
        "#!/bin/sh",
        f"# Generated by Docker Automation Manager v{__version__}",
        f"# Exported: {datetime.now().isoformat(timespec='seconds')}",
        "#",
        "# Usage: chmod +x this_file.sh && ./this_file.sh",
        "# Review settings before running, especially volume paths and IPs.",
        "",
    ]

    for cfg in configs:
        lines.append(f"# {'=' * 60}")
        lines.append(f"# Container: {cfg.name}")
        lines.append(f"# Image:     {cfg.image}")
        lines.append(f"# {'=' * 60}")
        lines.append("")
        lines.extend(_build_docker_run_command(cfg))
        lines.append("")

    return "\n".join(lines)


def _build_docker_run_command(cfg: ContainerConfig) -> list[str]:
    """Build the docker run command lines for a single container."""
    parts = ["docker run -d \\"]
    indent = "  "

    parts.append(f"{indent}--name {shlex.quote(cfg.name)} \\")
    parts.append(f"{indent}--restart {cfg.restart_policy} \\")

    if cfg.privileged:
        parts.append(f"{indent}--privileged \\")

    for cap in cfg.cap_add:
        parts.append(f"{indent}--cap-add {cap} \\")
    for cap in cfg.cap_drop:
        parts.append(f"{indent}--cap-drop {cap} \\")

    # Network
    network_mode = cfg.network_mode
    primary_ip = cfg.primary_ip()
    primary_net = cfg.primary_network()

    if network_mode in ("host", "none"):
        parts.append(f"{indent}--network {network_mode} \\")
    elif network_mode.startswith("container:"):
        parts.append(f"{indent}--network {network_mode} \\")
    else:
        parts.append(f"{indent}--network {primary_net} \\")
        if primary_ip:
            parts.append(f"{indent}--ip {primary_ip} \\")

    # Ports
    for p in cfg.ports:
        if p.host_ip:
            parts.append(f"{indent}-p {p.host_ip}:{p.host_port}:{p.container_port} \\")
        else:
            parts.append(f"{indent}-p {p.host_port}:{p.container_port} \\")

    # Volumes
    for bind in cfg.binds:
        parts.append(f"{indent}-v {shlex.quote(bind)} \\")

    # Environment
    for key, val in cfg.env.items():
        safe_val = shlex.quote(str(val)) if val else '""'
        parts.append(f"{indent}-e {key}={safe_val} \\")

    # Extra hosts
    for host in cfg.extra_hosts:
        parts.append(f"{indent}--add-host {host} \\")

    # Devices
    for dev in cfg.devices:
        parts.append(f"{indent}--device {dev.host_path}:{dev.container_path}:{dev.permissions} \\")

    # Labels
    for key, val in cfg.labels.items():
        parts.append(f"{indent}--label {shlex.quote(key)}={shlex.quote(val)} \\")

    # Image (last line — remove trailing backslash)
    parts.append(f"{indent}{cfg.image}")

    # Fix trailing backslash on second-to-last line
    if len(parts) >= 2:
        last = parts[-1]
        second_last = parts[-2]
        if second_last.endswith(" \\"):
            parts[-2] = second_last  # already correct
        parts[-1] = last  # image line has no backslash

    return parts


# ------------------------------------------------------------
# Docker Compose export
# ------------------------------------------------------------

def export_compose(cfg: ContainerConfig, output_dir: Path) -> Path:
    """Export a single container as a docker-compose.yml service."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"{cfg.name}.compose.yml"

    document = _build_compose_document([cfg])
    with open(path, "w") as f:
        f.write(f"# Generated by Docker Automation Manager v{__version__}\n")
        f.write(f"# Exported: {datetime.now().isoformat(timespec='seconds')}\n\n")
        yaml.dump(document, f, default_flow_style=False, sort_keys=False)

    return path


def export_compose_multi(configs: list[ContainerConfig], output_dir: Path) -> Path:
    """Export multiple containers as a single docker-compose.yml stack."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "docker-compose.yml"

    document = _build_compose_document(configs)
    with open(path, "w") as f:
        f.write(f"# Generated by Docker Automation Manager v{__version__}\n")
        f.write(f"# Exported: {datetime.now().isoformat(timespec='seconds')}\n\n")
        yaml.dump(document, f, default_flow_style=False, sort_keys=False)

    return path


def _build_compose_document(configs: list[ContainerConfig]) -> dict:
    """Build a complete docker-compose document dict for one or more containers."""
    services = {}
    networks: dict = {}

    for cfg in configs:
        service: dict = {
            "image": cfg.image,
            "container_name": cfg.name,
            "restart": cfg.restart_policy,
        }

        if cfg.privileged:
            service["privileged"] = True

        if cfg.cap_add:
            service["cap_add"] = cfg.cap_add

        if cfg.cap_drop:
            service["cap_drop"] = cfg.cap_drop

        # Network
        network_mode = cfg.network_mode
        primary_ip = cfg.primary_ip()
        primary_net = cfg.primary_network()

        if network_mode in ("host", "none"):
            service["network_mode"] = network_mode
        elif network_mode.startswith("container:"):
            service["network_mode"] = network_mode
        else:
            net_config: dict = {}
            if primary_ip:
                net_config["ipv4_address"] = primary_ip
            service["networks"] = {primary_net: net_config or None}
            # Register network in top-level networks section
            if primary_net not in networks:
                networks[primary_net] = {"external": True}

        # Ports
        if cfg.ports:
            service["ports"] = [
                f"{p.host_ip + ':' if p.host_ip else ''}{p.host_port}:{p.container_port}"
                for p in cfg.ports
            ]

        # Volumes
        if cfg.binds:
            service["volumes"] = cfg.binds

        # Environment
        if cfg.env:
            service["environment"] = {k: v for k, v in cfg.env.items()}

        # Extra hosts
        if cfg.extra_hosts:
            service["extra_hosts"] = cfg.extra_hosts

        # Devices
        if cfg.devices:
            service["devices"] = [
                f"{d.host_path}:{d.container_path}"
                for d in cfg.devices
            ]

        # Labels
        if cfg.labels:
            service["labels"] = cfg.labels

        services[cfg.name] = service

    document: dict = {"services": services}
    if networks:
        document["networks"] = networks

    return document


# ------------------------------------------------------------
# Unified export dispatcher
# ------------------------------------------------------------

class Exporter:
    """
    Unified export interface. Dispatches to the appropriate format handler.
    """

    def export(
        self,
        configs: list[ContainerConfig],
        fmt: str,
        output_dir: Path,
        single_file: bool = False,
    ) -> list[Path]:
        """
        Export containers to the specified format.

        Args:
            configs:     List of ContainerConfig objects to export
            fmt:         One of 'dam-yaml', 'docker-run', 'compose'
            output_dir:  Directory to write files into
            single_file: If True, combine all containers into one file
                         (only applicable for docker-run and compose)

        Returns:
            List of paths to exported files.
        """
        if fmt not in FORMATS:
            raise ValueError(f"Unknown export format '{fmt}'. Choose from: {', '.join(FORMATS)}")

        if not configs:
            return []

        output_dir = Path(output_dir)

        if fmt == "dam-yaml":
            if single_file or len(configs) > 1:
                return [export_dam_yaml_multi(configs, output_dir)]
            return [export_dam_yaml(configs[0], output_dir)]

        if fmt == "docker-run":
            if single_file or len(configs) > 1:
                return [export_docker_run_multi(configs, output_dir)]
            return [export_docker_run(configs[0], output_dir)]

        if fmt == "compose":
            if single_file or len(configs) > 1:
                return [export_compose_multi(configs, output_dir)]
            return [export_compose(configs[0], output_dir)]

        return []

    def export_all_formats(
        self,
        configs: list[ContainerConfig],
        output_dir: Path,
    ) -> dict[str, list[Path]]:
        """Export all containers in all three formats at once."""
        results = {}
        for fmt in FORMATS:
            results[fmt] = self.export(configs, fmt, output_dir / fmt, single_file=True)
        return results


# ------------------------------------------------------------
# Internal serialization helper (shared with importer)
# ------------------------------------------------------------

def _config_to_dict(cfg: ContainerConfig) -> dict:
    """Serialize a ContainerConfig to a plain dict for YAML output."""
    return {
        "name": cfg.name,
        "image": cfg.image,
        "image_id": cfg.image_id,
        "status": cfg.status,
        "restart_policy": cfg.restart_policy,
        "network_mode": cfg.network_mode,
        "networks": [
            {
                "name": n.name,
                "driver": n.driver,
                "ip_address": n.ip_address,
                "mac_address": n.mac_address,
                "is_static": n.is_static,
            }
            for n in cfg.networks
        ],
        "ports": [
            {
                "container_port": p.container_port,
                "host_ip": p.host_ip,
                "host_port": p.host_port,
            }
            for p in cfg.ports
        ],
        "binds": cfg.binds,
        "env": cfg.env,
        "privileged": cfg.privileged,
        "cap_add": cfg.cap_add,
        "cap_drop": cfg.cap_drop,
        "devices": [
            {
                "host_path": d.host_path,
                "container_path": d.container_path,
                "permissions": d.permissions,
            }
            for d in cfg.devices
        ],
        "extra_hosts": cfg.extra_hosts,
        "labels": cfg.labels,
        "version_strategy": cfg.version_strategy,
        "pinned_digest": cfg.pinned_digest,
    }
